require("dotenv").config();
var bodyParser = require("body-parser");
var express = require("express");
var App = express();
var DB = require("./sql");
App.use(bodyParser.urlencoded({ extended: false }));
App.use(bodyParser.json());
App.use(require("./module/jayware.js"));
App.use("/api/v1", require("./apis/v1.js"));
App.listen(process.env.PORT);
